package com.sams.custom.model;

import java.util.Date;

public class DAccountPosition {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_ID
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private Long apId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apChannelProductCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_INDI_OR_INST
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apIndiOrInst;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_FUND_ACCO
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apFundAcco;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apSubscribeCfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apSubscribeNoCfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_REDEMPTION_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apRedemptionCfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_REDEMPTION_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apRedemptionNoCfm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_CTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private Date apCtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_UTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private Date apUtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_CUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apCuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column D_ACCOUNT_POSITION.AP_UUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    private String apUuser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_ID
     *
     * @return the value of D_ACCOUNT_POSITION.AP_ID
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public Long getApId() {
        return apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_ID
     *
     * @param apId the value for D_ACCOUNT_POSITION.AP_ID
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApId(Long apId) {
        this.apId = apId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_CHANNEL_CODE
     *
     * @return the value of D_ACCOUNT_POSITION.AP_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApChannelCode() {
        return apChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_CHANNEL_CODE
     *
     * @param apChannelCode the value for D_ACCOUNT_POSITION.AP_CHANNEL_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApChannelCode(String apChannelCode) {
        this.apChannelCode = apChannelCode == null ? null : apChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_CHANNEL_PRODUCT_CODE
     *
     * @return the value of D_ACCOUNT_POSITION.AP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApChannelProductCode() {
        return apChannelProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_CHANNEL_PRODUCT_CODE
     *
     * @param apChannelProductCode the value for D_ACCOUNT_POSITION.AP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApChannelProductCode(String apChannelProductCode) {
        this.apChannelProductCode = apChannelProductCode == null ? null : apChannelProductCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_INDI_OR_INST
     *
     * @return the value of D_ACCOUNT_POSITION.AP_INDI_OR_INST
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApIndiOrInst() {
        return apIndiOrInst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_INDI_OR_INST
     *
     * @param apIndiOrInst the value for D_ACCOUNT_POSITION.AP_INDI_OR_INST
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApIndiOrInst(String apIndiOrInst) {
        this.apIndiOrInst = apIndiOrInst == null ? null : apIndiOrInst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_FUND_ACCO
     *
     * @return the value of D_ACCOUNT_POSITION.AP_FUND_ACCO
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApFundAcco() {
        return apFundAcco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_FUND_ACCO
     *
     * @param apFundAcco the value for D_ACCOUNT_POSITION.AP_FUND_ACCO
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApFundAcco(String apFundAcco) {
        this.apFundAcco = apFundAcco == null ? null : apFundAcco.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_CFM
     *
     * @return the value of D_ACCOUNT_POSITION.AP_SUBSCRIBE_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApSubscribeCfm() {
        return apSubscribeCfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_CFM
     *
     * @param apSubscribeCfm the value for D_ACCOUNT_POSITION.AP_SUBSCRIBE_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApSubscribeCfm(String apSubscribeCfm) {
        this.apSubscribeCfm = apSubscribeCfm == null ? null : apSubscribeCfm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_NO_CFM
     *
     * @return the value of D_ACCOUNT_POSITION.AP_SUBSCRIBE_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApSubscribeNoCfm() {
        return apSubscribeNoCfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_SUBSCRIBE_NO_CFM
     *
     * @param apSubscribeNoCfm the value for D_ACCOUNT_POSITION.AP_SUBSCRIBE_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApSubscribeNoCfm(String apSubscribeNoCfm) {
        this.apSubscribeNoCfm = apSubscribeNoCfm == null ? null : apSubscribeNoCfm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_REDEMPTION_CFM
     *
     * @return the value of D_ACCOUNT_POSITION.AP_REDEMPTION_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApRedemptionCfm() {
        return apRedemptionCfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_REDEMPTION_CFM
     *
     * @param apRedemptionCfm the value for D_ACCOUNT_POSITION.AP_REDEMPTION_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApRedemptionCfm(String apRedemptionCfm) {
        this.apRedemptionCfm = apRedemptionCfm == null ? null : apRedemptionCfm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_REDEMPTION_NO_CFM
     *
     * @return the value of D_ACCOUNT_POSITION.AP_REDEMPTION_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApRedemptionNoCfm() {
        return apRedemptionNoCfm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_REDEMPTION_NO_CFM
     *
     * @param apRedemptionNoCfm the value for D_ACCOUNT_POSITION.AP_REDEMPTION_NO_CFM
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApRedemptionNoCfm(String apRedemptionNoCfm) {
        this.apRedemptionNoCfm = apRedemptionNoCfm == null ? null : apRedemptionNoCfm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_CTIME
     *
     * @return the value of D_ACCOUNT_POSITION.AP_CTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public Date getApCtime() {
        return apCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_CTIME
     *
     * @param apCtime the value for D_ACCOUNT_POSITION.AP_CTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApCtime(Date apCtime) {
        this.apCtime = apCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_UTIME
     *
     * @return the value of D_ACCOUNT_POSITION.AP_UTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public Date getApUtime() {
        return apUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_UTIME
     *
     * @param apUtime the value for D_ACCOUNT_POSITION.AP_UTIME
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApUtime(Date apUtime) {
        this.apUtime = apUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_CUSER
     *
     * @return the value of D_ACCOUNT_POSITION.AP_CUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApCuser() {
        return apCuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_CUSER
     *
     * @param apCuser the value for D_ACCOUNT_POSITION.AP_CUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApCuser(String apCuser) {
        this.apCuser = apCuser == null ? null : apCuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column D_ACCOUNT_POSITION.AP_UUSER
     *
     * @return the value of D_ACCOUNT_POSITION.AP_UUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public String getApUuser() {
        return apUuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column D_ACCOUNT_POSITION.AP_UUSER
     *
     * @param apUuser the value for D_ACCOUNT_POSITION.AP_UUSER
     *
     * @mbggenerated Mon Apr 22 09:33:46 CST 2019
     */
    public void setApUuser(String apUuser) {
        this.apUuser = apUuser == null ? null : apUuser.trim();
    }
}