package com.sams.custom.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Table;

@Table(name = "P_PRODUCT_INFO")
public class PProductInfo implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_ID
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private Long piId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRODUCT_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProductType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piChannelProductCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_NAME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piChannelProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMinBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMinBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiBidsDiffAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstBidsDiffAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMaxBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMaxBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMinAppBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMinAppBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiAppBidsDiffAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstAppBidsDiffAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMaxAppBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMaxAppBidsAmt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMinRedeemVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMinRedeemVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiRedeemDiff;

    private BigDecimal piAccuExplainBuyLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstRedeemDiff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMaxVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMaxVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piIndiMinVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piInstMinVol;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CHANNEL_RATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piChannelRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PAY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piPayType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_IPO_BEGIN_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piIpoBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_IPO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piIpoEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRO_SETUP_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProSetupDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRO_YIELD_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProYieldType="0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRO_YIELD
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private BigDecimal piProYield;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_FEE_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piFeeFlag="0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INDI_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piIndiBuyFlag="0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_INST_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piInstBuyFlag="0";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRO_CFM_WAY
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProCfmWay="1";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CHECK_STATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piCheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private Date piCtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_UTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private Date piUtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piCuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_UUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piUuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_CURRENCY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piCurrencyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_ANNU_CAL_DAYS
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piAnnuCalDays="365";

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_PRODUCT_TOTAL_SHARE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piProductTotalShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_PRODUCT_INFO.PI_VALID_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    private String piValidFlag;

    private BigDecimal piMinIndiAmountRaised;
    private BigDecimal piMaxIndiAmountRaised;
    private BigDecimal piMinInstAmountRaised;
    private BigDecimal piMaxInstAmountRaised;
    private BigDecimal piMaxAmountRaised;
    private String piAction;
    private String piProCalculateType;
    private String piTemplateCode;
    private String piBatchNumber;
    private String piChannelCode;
    private String piSubChannelCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_ID
     *
     * @return the value of P_PRODUCT_INFO.PI_ID
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public Long getPiId() {
        return piId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_ID
     *
     * @param piId the value for P_PRODUCT_INFO.PI_ID
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiId(Long piId) {
        this.piId = piId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRODUCT_TYPE
     *
     * @return the value of P_PRODUCT_INFO.PI_PRODUCT_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProductType() {
        return piProductType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRODUCT_TYPE
     *
     * @param piProductType the value for P_PRODUCT_INFO.PI_PRODUCT_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProductType(String piProductType) {
        this.piProductType = piProductType == null ? null : piProductType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_CODE
     *
     * @return the value of P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiChannelProductCode() {
        return piChannelProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_CODE
     *
     * @param piChannelProductCode the value for P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiChannelProductCode(String piChannelProductCode) {
        this.piChannelProductCode = piChannelProductCode == null ? null : piChannelProductCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_NAME
     *
     * @return the value of P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_NAME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiChannelProductName() {
        return piChannelProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_NAME
     *
     * @param piChannelProductName the value for P_PRODUCT_INFO.PI_CHANNEL_PRODUCT_NAME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiChannelProductName(String piChannelProductName) {
        this.piChannelProductName = piChannelProductName == null ? null : piChannelProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMinBidsAmt() {
        return piIndiMinBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_BIDS_AMT
     *
     * @param piIndiMinBidsAmt the value for P_PRODUCT_INFO.PI_INDI_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMinBidsAmt(BigDecimal piIndiMinBidsAmt) {
        this.piIndiMinBidsAmt = piIndiMinBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MIN_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMinBidsAmt() {
        return piInstMinBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MIN_BIDS_AMT
     *
     * @param piInstMinBidsAmt the value for P_PRODUCT_INFO.PI_INST_MIN_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMinBidsAmt(BigDecimal piInstMinBidsAmt) {
        this.piInstMinBidsAmt = piInstMinBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_BIDS_DIFF_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiBidsDiffAmt() {
        return piIndiBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_BIDS_DIFF_AMT
     *
     * @param piIndiBidsDiffAmt the value for P_PRODUCT_INFO.PI_INDI_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiBidsDiffAmt(BigDecimal piIndiBidsDiffAmt) {
        this.piIndiBidsDiffAmt = piIndiBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_BIDS_DIFF_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstBidsDiffAmt() {
        return piInstBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_BIDS_DIFF_AMT
     *
     * @param piInstBidsDiffAmt the value for P_PRODUCT_INFO.PI_INST_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstBidsDiffAmt(BigDecimal piInstBidsDiffAmt) {
        this.piInstBidsDiffAmt = piInstBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMaxBidsAmt() {
        return piIndiMaxBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_BIDS_AMT
     *
     * @param piIndiMaxBidsAmt the value for P_PRODUCT_INFO.PI_INDI_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMaxBidsAmt(BigDecimal piIndiMaxBidsAmt) {
        this.piIndiMaxBidsAmt = piIndiMaxBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MAX_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMaxBidsAmt() {
        return piInstMaxBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MAX_BIDS_AMT
     *
     * @param piInstMaxBidsAmt the value for P_PRODUCT_INFO.PI_INST_MAX_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMaxBidsAmt(BigDecimal piInstMaxBidsAmt) {
        this.piInstMaxBidsAmt = piInstMaxBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_APP_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMinAppBidsAmt() {
        return piIndiMinAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_APP_BIDS_AMT
     *
     * @param piIndiMinAppBidsAmt the value for P_PRODUCT_INFO.PI_INDI_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMinAppBidsAmt(BigDecimal piIndiMinAppBidsAmt) {
        this.piIndiMinAppBidsAmt = piIndiMinAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MIN_APP_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMinAppBidsAmt() {
        return piInstMinAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MIN_APP_BIDS_AMT
     *
     * @param piInstMinAppBidsAmt the value for P_PRODUCT_INFO.PI_INST_MIN_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMinAppBidsAmt(BigDecimal piInstMinAppBidsAmt) {
        this.piInstMinAppBidsAmt = piInstMinAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_APP_BIDS_DIFF_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiAppBidsDiffAmt() {
        return piIndiAppBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_APP_BIDS_DIFF_AMT
     *
     * @param piIndiAppBidsDiffAmt the value for P_PRODUCT_INFO.PI_INDI_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiAppBidsDiffAmt(BigDecimal piIndiAppBidsDiffAmt) {
        this.piIndiAppBidsDiffAmt = piIndiAppBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_APP_BIDS_DIFF_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstAppBidsDiffAmt() {
        return piInstAppBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_APP_BIDS_DIFF_AMT
     *
     * @param piInstAppBidsDiffAmt the value for P_PRODUCT_INFO.PI_INST_APP_BIDS_DIFF_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstAppBidsDiffAmt(BigDecimal piInstAppBidsDiffAmt) {
        this.piInstAppBidsDiffAmt = piInstAppBidsDiffAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_APP_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMaxAppBidsAmt() {
        return piIndiMaxAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_APP_BIDS_AMT
     *
     * @param piIndiMaxAppBidsAmt the value for P_PRODUCT_INFO.PI_INDI_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMaxAppBidsAmt(BigDecimal piIndiMaxAppBidsAmt) {
        this.piIndiMaxAppBidsAmt = piIndiMaxAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MAX_APP_BIDS_AMT
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMaxAppBidsAmt() {
        return piInstMaxAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MAX_APP_BIDS_AMT
     *
     * @param piInstMaxAppBidsAmt the value for P_PRODUCT_INFO.PI_INST_MAX_APP_BIDS_AMT
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMaxAppBidsAmt(BigDecimal piInstMaxAppBidsAmt) {
        this.piInstMaxAppBidsAmt = piInstMaxAppBidsAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_REDEEM_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMinRedeemVol() {
        return piIndiMinRedeemVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_REDEEM_VOL
     *
     * @param piIndiMinRedeemVol the value for P_PRODUCT_INFO.PI_INDI_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMinRedeemVol(BigDecimal piIndiMinRedeemVol) {
        this.piIndiMinRedeemVol = piIndiMinRedeemVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MIN_REDEEM_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMinRedeemVol() {
        return piInstMinRedeemVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MIN_REDEEM_VOL
     *
     * @param piInstMinRedeemVol the value for P_PRODUCT_INFO.PI_INST_MIN_REDEEM_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMinRedeemVol(BigDecimal piInstMinRedeemVol) {
        this.piInstMinRedeemVol = piInstMinRedeemVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_REDEEM_DIFF
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiRedeemDiff() {
        return piIndiRedeemDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_REDEEM_DIFF
     *
     * @param piIndiRedeemDiff the value for P_PRODUCT_INFO.PI_INDI_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiRedeemDiff(BigDecimal piIndiRedeemDiff) {
        this.piIndiRedeemDiff = piIndiRedeemDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_REDEEM_DIFF
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstRedeemDiff() {
        return piInstRedeemDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_REDEEM_DIFF
     *
     * @param piInstRedeemDiff the value for P_PRODUCT_INFO.PI_INST_REDEEM_DIFF
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstRedeemDiff(BigDecimal piInstRedeemDiff) {
        this.piInstRedeemDiff = piInstRedeemDiff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMaxVol() {
        return piIndiMaxVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MAX_VOL
     *
     * @param piIndiMaxVol the value for P_PRODUCT_INFO.PI_INDI_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMaxVol(BigDecimal piIndiMaxVol) {
        this.piIndiMaxVol = piIndiMaxVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MAX_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMaxVol() {
        return piInstMaxVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MAX_VOL
     *
     * @param piInstMaxVol the value for P_PRODUCT_INFO.PI_INST_MAX_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMaxVol(BigDecimal piInstMaxVol) {
        this.piInstMaxVol = piInstMaxVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiIndiMinVol() {
        return piIndiMinVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_MIN_VOL
     *
     * @param piIndiMinVol the value for P_PRODUCT_INFO.PI_INDI_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiMinVol(BigDecimal piIndiMinVol) {
        this.piIndiMinVol = piIndiMinVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_MIN_VOL
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiInstMinVol() {
        return piInstMinVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_MIN_VOL
     *
     * @param piInstMinVol the value for P_PRODUCT_INFO.PI_INST_MIN_VOL
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstMinVol(BigDecimal piInstMinVol) {
        this.piInstMinVol = piInstMinVol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CHANNEL_RATE
     *
     * @return the value of P_PRODUCT_INFO.PI_CHANNEL_RATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiChannelRate() {
        return piChannelRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CHANNEL_RATE
     *
     * @param piChannelRate the value for P_PRODUCT_INFO.PI_CHANNEL_RATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiChannelRate(BigDecimal piChannelRate) {
        this.piChannelRate = piChannelRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PAY_TYPE
     *
     * @return the value of P_PRODUCT_INFO.PI_PAY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiPayType() {
        return piPayType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PAY_TYPE
     *
     * @param piPayType the value for P_PRODUCT_INFO.PI_PAY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiPayType(String piPayType) {
        this.piPayType = piPayType == null ? null : piPayType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_IPO_BEGIN_DATE
     *
     * @return the value of P_PRODUCT_INFO.PI_IPO_BEGIN_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiIpoBeginDate() {
        return piIpoBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_IPO_BEGIN_DATE
     *
     * @param piIpoBeginDate the value for P_PRODUCT_INFO.PI_IPO_BEGIN_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIpoBeginDate(String piIpoBeginDate) {
        this.piIpoBeginDate = piIpoBeginDate == null ? null : piIpoBeginDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_IPO_END_DATE
     *
     * @return the value of P_PRODUCT_INFO.PI_IPO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiIpoEndDate() {
        return piIpoEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_IPO_END_DATE
     *
     * @param piIpoEndDate the value for P_PRODUCT_INFO.PI_IPO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIpoEndDate(String piIpoEndDate) {
        this.piIpoEndDate = piIpoEndDate == null ? null : piIpoEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRO_SETUP_DATE
     *
     * @return the value of P_PRODUCT_INFO.PI_PRO_SETUP_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProSetupDate() {
        return piProSetupDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRO_SETUP_DATE
     *
     * @param piProSetupDate the value for P_PRODUCT_INFO.PI_PRO_SETUP_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProSetupDate(String piProSetupDate) {
        this.piProSetupDate = piProSetupDate == null ? null : piProSetupDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRO_END_DATE
     *
     * @return the value of P_PRODUCT_INFO.PI_PRO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProEndDate() {
        return piProEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRO_END_DATE
     *
     * @param piProEndDate the value for P_PRODUCT_INFO.PI_PRO_END_DATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProEndDate(String piProEndDate) {
        this.piProEndDate = piProEndDate == null ? null : piProEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRO_YIELD_TYPE
     *
     * @return the value of P_PRODUCT_INFO.PI_PRO_YIELD_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProYieldType() {
        return piProYieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRO_YIELD_TYPE
     *
     * @param piProYieldType the value for P_PRODUCT_INFO.PI_PRO_YIELD_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProYieldType(String piProYieldType) {
        this.piProYieldType = piProYieldType == null ? null : piProYieldType.trim();
    }


    public BigDecimal getPiAccuExplainBuyLimit() {
        return piAccuExplainBuyLimit;
    }

    public void setPiAccuExplainBuyLimit(BigDecimal piAccuExplainBuyLimit) {
        this.piAccuExplainBuyLimit = piAccuExplainBuyLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRO_YIELD
     *
     * @return the value of P_PRODUCT_INFO.PI_PRO_YIELD
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public BigDecimal getPiProYield() {
        return piProYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRO_YIELD
     *
     * @param piProYield the value for P_PRODUCT_INFO.PI_PRO_YIELD
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProYield(BigDecimal piProYield) {
        this.piProYield = piProYield;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_FEE_FLAG
     *
     * @return the value of P_PRODUCT_INFO.PI_FEE_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiFeeFlag() {
        return piFeeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_FEE_FLAG
     *
     * @param piFeeFlag the value for P_PRODUCT_INFO.PI_FEE_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiFeeFlag(String piFeeFlag) {
        this.piFeeFlag = piFeeFlag == null ? null : piFeeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INDI_BUY_FLAG
     *
     * @return the value of P_PRODUCT_INFO.PI_INDI_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiIndiBuyFlag() {
        return piIndiBuyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INDI_BUY_FLAG
     *
     * @param piIndiBuyFlag the value for P_PRODUCT_INFO.PI_INDI_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiIndiBuyFlag(String piIndiBuyFlag) {
        this.piIndiBuyFlag = piIndiBuyFlag == null ? null : piIndiBuyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_INST_BUY_FLAG
     *
     * @return the value of P_PRODUCT_INFO.PI_INST_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiInstBuyFlag() {
        return piInstBuyFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_INST_BUY_FLAG
     *
     * @param piInstBuyFlag the value for P_PRODUCT_INFO.PI_INST_BUY_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiInstBuyFlag(String piInstBuyFlag) {
        this.piInstBuyFlag = piInstBuyFlag == null ? null : piInstBuyFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRO_CFM_WAY
     *
     * @return the value of P_PRODUCT_INFO.PI_PRO_CFM_WAY
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProCfmWay() {
        return piProCfmWay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRO_CFM_WAY
     *
     * @param piProCfmWay the value for P_PRODUCT_INFO.PI_PRO_CFM_WAY
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProCfmWay(String piProCfmWay) {
        this.piProCfmWay = piProCfmWay == null ? null : piProCfmWay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CHECK_STATE
     *
     * @return the value of P_PRODUCT_INFO.PI_CHECK_STATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiCheckState() {
        return piCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CHECK_STATE
     *
     * @param piCheckState the value for P_PRODUCT_INFO.PI_CHECK_STATE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiCheckState(String piCheckState) {
        this.piCheckState = piCheckState == null ? null : piCheckState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CTIME
     *
     * @return the value of P_PRODUCT_INFO.PI_CTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public Date getPiCtime() {
        return piCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CTIME
     *
     * @param piCtime the value for P_PRODUCT_INFO.PI_CTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiCtime(Date piCtime) {
        this.piCtime = piCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_UTIME
     *
     * @return the value of P_PRODUCT_INFO.PI_UTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public Date getPiUtime() {
        return piUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_UTIME
     *
     * @param piUtime the value for P_PRODUCT_INFO.PI_UTIME
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiUtime(Date piUtime) {
        this.piUtime = piUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CUSER
     *
     * @return the value of P_PRODUCT_INFO.PI_CUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiCuser() {
        return piCuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CUSER
     *
     * @param piCuser the value for P_PRODUCT_INFO.PI_CUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiCuser(String piCuser) {
        this.piCuser = piCuser == null ? null : piCuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_UUSER
     *
     * @return the value of P_PRODUCT_INFO.PI_UUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiUuser() {
        return piUuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_UUSER
     *
     * @param piUuser the value for P_PRODUCT_INFO.PI_UUSER
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiUuser(String piUuser) {
        this.piUuser = piUuser == null ? null : piUuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_CURRENCY_TYPE
     *
     * @return the value of P_PRODUCT_INFO.PI_CURRENCY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiCurrencyType() {
        return piCurrencyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_CURRENCY_TYPE
     *
     * @param piCurrencyType the value for P_PRODUCT_INFO.PI_CURRENCY_TYPE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiCurrencyType(String piCurrencyType) {
        this.piCurrencyType = piCurrencyType == null ? null : piCurrencyType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_ANNU_CAL_DAYS
     *
     * @return the value of P_PRODUCT_INFO.PI_ANNU_CAL_DAYS
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiAnnuCalDays() {
        return piAnnuCalDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_ANNU_CAL_DAYS
     *
     * @param piAnnuCalDays the value for P_PRODUCT_INFO.PI_ANNU_CAL_DAYS
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiAnnuCalDays(String piAnnuCalDays) {
        this.piAnnuCalDays = piAnnuCalDays == null ? null : piAnnuCalDays.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_PRODUCT_TOTAL_SHARE
     *
     * @return the value of P_PRODUCT_INFO.PI_PRODUCT_TOTAL_SHARE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiProductTotalShare() {
        return piProductTotalShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_PRODUCT_TOTAL_SHARE
     *
     * @param piProductTotalShare the value for P_PRODUCT_INFO.PI_PRODUCT_TOTAL_SHARE
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiProductTotalShare(String piProductTotalShare) {
        this.piProductTotalShare = piProductTotalShare == null ? null : piProductTotalShare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_PRODUCT_INFO.PI_VALID_FLAG
     *
     * @return the value of P_PRODUCT_INFO.PI_VALID_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public String getPiValidFlag() {
        return piValidFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_PRODUCT_INFO.PI_VALID_FLAG
     *
     * @param piValidFlag the value for P_PRODUCT_INFO.PI_VALID_FLAG
     *
     * @mbggenerated Thu Apr 18 17:45:58 CST 2019
     */
    public void setPiValidFlag(String piValidFlag) {
        this.piValidFlag = piValidFlag == null ? null : piValidFlag.trim();
    }


    public BigDecimal getPiMinIndiAmountRaised() {
        return piMinIndiAmountRaised;
    }

    public void setPiMinIndiAmountRaised(BigDecimal piMinIndiAmountRaised) {
        this.piMinIndiAmountRaised = piMinIndiAmountRaised;
    }

    public BigDecimal getPiMaxIndiAmountRaised() {
        return piMaxIndiAmountRaised;
    }

    public void setPiMaxIndiAmountRaised(BigDecimal piMaxIndiAmountRaised) {
        this.piMaxIndiAmountRaised = piMaxIndiAmountRaised;
    }

    public BigDecimal getPiMinInstAmountRaised() {
        return piMinInstAmountRaised;
    }

    public void setPiMinInstAmountRaised(BigDecimal piMinInstAmountRaised) {
        this.piMinInstAmountRaised = piMinInstAmountRaised;
    }

    public BigDecimal getPiMaxInstAmountRaised() {
        return piMaxInstAmountRaised;
    }

    public void setPiMaxInstAmountRaised(BigDecimal piMaxInstAmountRaised) {
        this.piMaxInstAmountRaised = piMaxInstAmountRaised;
    }

    public BigDecimal getPiMaxAmountRaised() {
        return piMaxAmountRaised;
    }

    public void setPiMaxAmountRaised(BigDecimal piMaxAmountRaised) {
        this.piMaxAmountRaised = piMaxAmountRaised;
    }

    public String getPiAction() {
        return piAction;
    }

    public void setPiAction(String piAction) {
        this.piAction = piAction;
    }

    public String getPiProCalculateType() {
        return piProCalculateType;
    }

    public void setPiProCalculateType(String piProCalculateType) {
        this.piProCalculateType = piProCalculateType;
    }

    public String getPiTemplateCode() {
        return piTemplateCode;
    }

    public void setPiTemplateCode(String piTemplateCode) {
        this.piTemplateCode = piTemplateCode;
    }

    public String getPiBatchNumber() {
        return piBatchNumber;
    }

    public void setPiBatchNumber(String piBatchNumber) {
        this.piBatchNumber = piBatchNumber;
    }

    public String getPiChannelCode() {
        return piChannelCode;
    }

    public void setPiChannelCode(String piChannelCode) {
        this.piChannelCode = piChannelCode;
    }

    public String getPiSubChannelCode() {
        return piSubChannelCode;
    }

    public void setPiSubChannelCode(String piSubChannelCode) {
        this.piSubChannelCode = piSubChannelCode;
    }

    public PProductInfo() {
        super();
    }

    public PProductInfo(Long piId, String piProductType, String piChannelProductCode, String piChannelProductName,
                        BigDecimal piIndiMinBidsAmt, BigDecimal piInstMinBidsAmt, BigDecimal piIndiBidsDiffAmt,
                        BigDecimal piInstBidsDiffAmt, BigDecimal piIndiMaxBidsAmt, BigDecimal piInstMaxBidsAmt,
                        BigDecimal piIndiMinAppBidsAmt, BigDecimal piInstMinAppBidsAmt, BigDecimal piIndiAppBidsDiffAmt,
                        BigDecimal piInstAppBidsDiffAmt, BigDecimal piIndiMaxAppBidsAmt, BigDecimal piInstMaxAppBidsAmt,
                        BigDecimal piIndiMinRedeemVol, BigDecimal piInstMinRedeemVol, BigDecimal piIndiRedeemDiff,
                        BigDecimal piAccuExplainBuyLimit, BigDecimal piInstRedeemDiff, BigDecimal piIndiMaxVol,
                        BigDecimal piInstMaxVol, BigDecimal piIndiMinVol, BigDecimal piInstMinVol, BigDecimal piChannelRate,
                        String piPayType, String piIpoBeginDate, String piIpoEndDate, String piProSetupDate, String piProEndDate,
                        String piProYieldType, BigDecimal piProYield, String piFeeFlag, String piIndiBuyFlag, String piInstBuyFlag,
                        String piProCfmWay, String piCheckState, Date piCtime, Date piUtime, String piCuser, String piUuser,
                        String piCurrencyType, String piAnnuCalDays, String piProductTotalShare, String piValidFlag,
                        BigDecimal piMinIndiAmountRaised, BigDecimal piMaxIndiAmountRaised, BigDecimal piMinInstAmountRaised,
                        BigDecimal piMaxInstAmountRaised, BigDecimal piMaxAmountRaised, String piAction, String piProCalculateType,
                        String piTemplateCode, String piBatchNumber, String piChannelCode,String piSubChannelCode) {
        super();
        this.piId = piId;
        this.piProductType = piProductType;
        this.piChannelProductCode = piChannelProductCode;
        this.piChannelProductName = piChannelProductName;
        this.piIndiMinBidsAmt = piIndiMinBidsAmt;
        this.piInstMinBidsAmt = piInstMinBidsAmt;
        this.piIndiBidsDiffAmt = piIndiBidsDiffAmt;
        this.piInstBidsDiffAmt = piInstBidsDiffAmt;
        this.piIndiMaxBidsAmt = piIndiMaxBidsAmt;
        this.piInstMaxBidsAmt = piInstMaxBidsAmt;
        this.piIndiMinAppBidsAmt = piIndiMinAppBidsAmt;
        this.piInstMinAppBidsAmt = piInstMinAppBidsAmt;
        this.piIndiAppBidsDiffAmt = piIndiAppBidsDiffAmt;
        this.piInstAppBidsDiffAmt = piInstAppBidsDiffAmt;
        this.piIndiMaxAppBidsAmt = piIndiMaxAppBidsAmt;
        this.piInstMaxAppBidsAmt = piInstMaxAppBidsAmt;
        this.piIndiMinRedeemVol = piIndiMinRedeemVol;
        this.piInstMinRedeemVol = piInstMinRedeemVol;
        this.piIndiRedeemDiff = piIndiRedeemDiff;
        this.piAccuExplainBuyLimit = piAccuExplainBuyLimit;
        this.piInstRedeemDiff = piInstRedeemDiff;
        this.piIndiMaxVol = piIndiMaxVol;
        this.piInstMaxVol = piInstMaxVol;
        this.piIndiMinVol = piIndiMinVol;
        this.piInstMinVol = piInstMinVol;
        this.piChannelRate = piChannelRate;
        this.piPayType = piPayType;
        this.piIpoBeginDate = piIpoBeginDate;
        this.piIpoEndDate = piIpoEndDate;
        this.piProSetupDate = piProSetupDate;
        this.piProEndDate = piProEndDate;
        this.piProYieldType = piProYieldType;
        this.piProYield = piProYield;
        this.piFeeFlag = piFeeFlag;
        this.piIndiBuyFlag = piIndiBuyFlag;
        this.piInstBuyFlag = piInstBuyFlag;
        this.piProCfmWay = piProCfmWay;
        this.piCheckState = piCheckState;
        this.piCtime = piCtime;
        this.piUtime = piUtime;
        this.piCuser = piCuser;
        this.piUuser = piUuser;
        this.piCurrencyType = piCurrencyType;
        this.piAnnuCalDays = piAnnuCalDays;
        this.piProductTotalShare = piProductTotalShare;
        this.piValidFlag = piValidFlag;
        this.piMinIndiAmountRaised = piMinIndiAmountRaised;
        this.piMaxIndiAmountRaised = piMaxIndiAmountRaised;
        this.piMinInstAmountRaised = piMinInstAmountRaised;
        this.piMaxInstAmountRaised = piMaxInstAmountRaised;
        this.piMaxAmountRaised = piMaxAmountRaised;
        this.piAction = piAction;
        this.piProCalculateType = piProCalculateType;
        this.piTemplateCode = piTemplateCode;
        this.piBatchNumber = piBatchNumber;
        this.piChannelCode = piChannelCode;
        this.piSubChannelCode = piSubChannelCode;
    }

    @Override
    public String toString() {
        return "PProductInfo [piId=" + piId + ", piProductType=" + piProductType + ", piChannelProductCode="
                + piChannelProductCode + ", piChannelProductName=" + piChannelProductName + ", piIndiMinBidsAmt="
                + piIndiMinBidsAmt + ", piInstMinBidsAmt=" + piInstMinBidsAmt + ", piIndiBidsDiffAmt="
                + piIndiBidsDiffAmt + ", piInstBidsDiffAmt=" + piInstBidsDiffAmt + ", piIndiMaxBidsAmt="
                + piIndiMaxBidsAmt + ", piInstMaxBidsAmt=" + piInstMaxBidsAmt + ", piIndiMinAppBidsAmt="
                + piIndiMinAppBidsAmt + ", piInstMinAppBidsAmt=" + piInstMinAppBidsAmt + ", piIndiAppBidsDiffAmt="
                + piIndiAppBidsDiffAmt + ", piInstAppBidsDiffAmt=" + piInstAppBidsDiffAmt + ", piIndiMaxAppBidsAmt="
                + piIndiMaxAppBidsAmt + ", piInstMaxAppBidsAmt=" + piInstMaxAppBidsAmt + ", piIndiMinRedeemVol="
                + piIndiMinRedeemVol + ", piInstMinRedeemVol=" + piInstMinRedeemVol + ", piIndiRedeemDiff="
                + piIndiRedeemDiff + ", piAccuExplainBuyLimit=" + piAccuExplainBuyLimit + ", piInstRedeemDiff="
                + piInstRedeemDiff + ", piIndiMaxVol=" + piIndiMaxVol + ", piInstMaxVol=" + piInstMaxVol
                + ", piIndiMinVol=" + piIndiMinVol + ", piInstMinVol=" + piInstMinVol + ", piChannelRate="
                + piChannelRate + ", piPayType=" + piPayType + ", piIpoBeginDate=" + piIpoBeginDate + ", piIpoEndDate="
                + piIpoEndDate + ", piProSetupDate=" + piProSetupDate + ", piProEndDate=" + piProEndDate
                + ", piProYieldType=" + piProYieldType + ", piProYield=" + piProYield + ", piFeeFlag=" + piFeeFlag
                + ", piIndiBuyFlag=" + piIndiBuyFlag + ", piInstBuyFlag=" + piInstBuyFlag + ", piProCfmWay="
                + piProCfmWay + ", piCheckState=" + piCheckState + ", piCtime=" + piCtime + ", piUtime=" + piUtime
                + ", piCuser=" + piCuser + ", piUuser=" + piUuser + ", piCurrencyType=" + piCurrencyType
                + ", piAnnuCalDays=" + piAnnuCalDays + ", piProductTotalShare=" + piProductTotalShare + ", piValidFlag="
                + piValidFlag + ", piMinIndiAmountRaised=" + piMinIndiAmountRaised + ", piMaxIndiAmountRaised="
                + piMaxIndiAmountRaised + ", piMinInstAmountRaised=" + piMinInstAmountRaised
                + ", piMaxInstAmountRaised=" + piMaxInstAmountRaised + ", piMaxAmountRaised=" + piMaxAmountRaised
                + ", piAction=" + piAction + ", piProCalculateType=" + piProCalculateType + ", piTemplateCode="
                + piTemplateCode + ", piBatchNumber=" + piBatchNumber + ", piChannelCode=" + piChannelCode + ",piSubChannelCode=" + piSubChannelCode + "]";
    }


}