
package com.sams.wsdl.S100512;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100512", targetNamespace = "http://www.example.org/S100512/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100512 {


    /**
     * 
     * @param common
     * @return
     *     returns com.sams.wsdl.S100512.S100512TypeResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/S100512/NewOperation")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100512/", partName = "Common")
    public S100512TypeResponse newOperation(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100512/", partName = "Common")
        S100512Type common);

}
