
package com.sams.wsdl.S100139;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100139", targetNamespace = "http://www.example.org/S100139/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100139 {


    /**
     * 
     * @param commonRq
     * @return
     *     returns com.sams.wsdl.S100139.S100139TypeResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/S100139/NewOperation")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100139/", partName = "CommonRs")
    public S100139TypeResponse newOperation(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100139/", partName = "CommonRq")
        S100139Type commonRq);

}
