
package com.sams.wsdl.S100040;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100040", targetNamespace = "http://www.example.org/S100040/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100040 {


    /**
     * 
     * @param common
     * @return
     *     returns com.sams.wsdl.S100040.S100040TypeResponse
     */
    @WebMethod(operationName = "S100040", action = "http://www.example.org/S100040/S100040")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100040/", partName = "Common")
    public S100040TypeResponse s100040(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100040/", partName = "Common")
        S100040Type common);

}
