
package com.sams.wsdl.S100434;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100434", targetNamespace = "http://www.example.org/S100434/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100434 {


    /**
     * 
     * @param common
     * @return
     *     returns com.sams.wsdl.S100434.S100434TypeResponse
     */
    @WebMethod(operationName = "S100434", action = "http://www.example.org/S100434/S100434")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100434/", partName = "Common")
    public S100434TypeResponse s100434(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100434/", partName = "Common")
        S100434Type common);

}
