package com.sams.custom.model;

import java.util.Date;

public class ChannelProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_ID
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private Long cpId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_CHANNEL_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpChannelCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpChannelProductCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpTaProductCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_NAME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpTaProductName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_CHECK_STATE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpCheckState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_CTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private Date cpCtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_UTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private Date cpUtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_CUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpCuser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column P_CHANNEL_PRODUCT.CP_UUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    private String cpUuser;
    
    private String cpAction;
    
    private String cpValidFlag;
    
    private String cpIsSetUp;
    
    private String cpBatchNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_ID
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_ID
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public Long getCpId() {
        return cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_ID
     *
     * @param cpId the value for P_CHANNEL_PRODUCT.CP_ID
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpId(Long cpId) {
        this.cpId = cpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_CHANNEL_CODE
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_CHANNEL_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpChannelCode() {
        return cpChannelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_CHANNEL_CODE
     *
     * @param cpChannelCode the value for P_CHANNEL_PRODUCT.CP_CHANNEL_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpChannelCode(String cpChannelCode) {
        this.cpChannelCode = cpChannelCode == null ? null : cpChannelCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_CHANNEL_PRODUCT_CODE
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpChannelProductCode() {
        return cpChannelProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_CHANNEL_PRODUCT_CODE
     *
     * @param cpChannelProductCode the value for P_CHANNEL_PRODUCT.CP_CHANNEL_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpChannelProductCode(String cpChannelProductCode) {
        this.cpChannelProductCode = cpChannelProductCode == null ? null : cpChannelProductCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_CODE
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_TA_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpTaProductCode() {
        return cpTaProductCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_CODE
     *
     * @param cpTaProductCode the value for P_CHANNEL_PRODUCT.CP_TA_PRODUCT_CODE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpTaProductCode(String cpTaProductCode) {
        this.cpTaProductCode = cpTaProductCode == null ? null : cpTaProductCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_NAME
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_TA_PRODUCT_NAME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpTaProductName() {
        return cpTaProductName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_TA_PRODUCT_NAME
     *
     * @param cpTaProductName the value for P_CHANNEL_PRODUCT.CP_TA_PRODUCT_NAME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpTaProductName(String cpTaProductName) {
        this.cpTaProductName = cpTaProductName == null ? null : cpTaProductName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_CHECK_STATE
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_CHECK_STATE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpCheckState() {
        return cpCheckState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_CHECK_STATE
     *
     * @param cpCheckState the value for P_CHANNEL_PRODUCT.CP_CHECK_STATE
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpCheckState(String cpCheckState) {
        this.cpCheckState = cpCheckState == null ? null : cpCheckState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_CTIME
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_CTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public Date getCpCtime() {
        return cpCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_CTIME
     *
     * @param cpCtime the value for P_CHANNEL_PRODUCT.CP_CTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpCtime(Date cpCtime) {
        this.cpCtime = cpCtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_UTIME
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_UTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public Date getCpUtime() {
        return cpUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_UTIME
     *
     * @param cpUtime the value for P_CHANNEL_PRODUCT.CP_UTIME
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpUtime(Date cpUtime) {
        this.cpUtime = cpUtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_CUSER
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_CUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpCuser() {
        return cpCuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_CUSER
     *
     * @param cpCuser the value for P_CHANNEL_PRODUCT.CP_CUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpCuser(String cpCuser) {
        this.cpCuser = cpCuser == null ? null : cpCuser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column P_CHANNEL_PRODUCT.CP_UUSER
     *
     * @return the value of P_CHANNEL_PRODUCT.CP_UUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public String getCpUuser() {
        return cpUuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column P_CHANNEL_PRODUCT.CP_UUSER
     *
     * @param cpUuser the value for P_CHANNEL_PRODUCT.CP_UUSER
     *
     * @mbggenerated Fri May 17 16:39:19 CST 2019
     */
    public void setCpUuser(String cpUuser) {
        this.cpUuser = cpUuser == null ? null : cpUuser.trim();
    }

	public String getCpAction() {
		return cpAction;
	}

	public void setCpAction(String cpAction) {
		this.cpAction = cpAction;
	}

	public String getCpValidFlag() {
		return cpValidFlag;
	}

	public void setCpValidFlag(String cpValidFlag) {
		this.cpValidFlag = cpValidFlag;
	}

	public String getCpIsSetUp() {
		return cpIsSetUp;
	}

	public void setCpIsSetUp(String cpIsSetUp) {
		this.cpIsSetUp = cpIsSetUp;
	}

	public String getCpBatchNumber() {
		return cpBatchNumber;
	}

	public void setCpBatchNumber(String cpBatchNumber) {
		this.cpBatchNumber = cpBatchNumber;
	}

	public ChannelProduct() {
		super();
	}

	public ChannelProduct(Long cpId, String cpChannelCode, String cpChannelProductCode, String cpTaProductCode,
			String cpTaProductName, String cpCheckState, Date cpCtime, Date cpUtime, String cpCuser, String cpUuser,
			String cpAction, String cpValidFlag, String cpIsSetUp, String cpBatchNumber) {
		super();
		this.cpId = cpId;
		this.cpChannelCode = cpChannelCode;
		this.cpChannelProductCode = cpChannelProductCode;
		this.cpTaProductCode = cpTaProductCode;
		this.cpTaProductName = cpTaProductName;
		this.cpCheckState = cpCheckState;
		this.cpCtime = cpCtime;
		this.cpUtime = cpUtime;
		this.cpCuser = cpCuser;
		this.cpUuser = cpUuser;
		this.cpAction = cpAction;
		this.cpValidFlag = cpValidFlag;
		this.cpIsSetUp = cpIsSetUp;
		this.cpBatchNumber = cpBatchNumber;
	}

	@Override
	public String toString() {
		return "ChannelProduct [cpId=" + cpId + ", cpChannelCode=" + cpChannelCode + ", cpChannelProductCode="
				+ cpChannelProductCode + ", cpTaProductCode=" + cpTaProductCode + ", cpTaProductName=" + cpTaProductName
				+ ", cpCheckState=" + cpCheckState + ", cpCtime=" + cpCtime + ", cpUtime=" + cpUtime + ", cpCuser="
				+ cpCuser + ", cpUuser=" + cpUuser + ", cpAction=" + cpAction + ", cpValidFlag=" + cpValidFlag
				+ ", cpIsSetUp=" + cpIsSetUp + ", cpBatchNumber=" + cpBatchNumber + "]";
	}

	
}