
package com.sams.wsdl.S100037;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100037", targetNamespace = "http://www.example.org/S100037/", wsdlLocation = "file:/D:/wsdl/S100037.wsdl")
public class S100037_Service
    extends Service
{

    private final static URL S100037_WSDL_LOCATION;
    private final static WebServiceException S100037_EXCEPTION;
    private final static QName S100037_QNAME = new QName("http://www.example.org/S100037/", "S100037");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/wsdl/S100037.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        S100037_WSDL_LOCATION = url;
        S100037_EXCEPTION = e;
    }

    public S100037_Service() {
        super(__getWsdlLocation(), S100037_QNAME);
    }

    public S100037_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100037_QNAME, features);
    }

    public S100037_Service(URL wsdlLocation) {
        super(wsdlLocation, S100037_QNAME);
    }

    public S100037_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100037_QNAME, features);
    }

    public S100037_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100037_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100037
     */
    @WebEndpoint(name = "S100037SOAP")
    public S100037 getS100037SOAP() {
        return super.getPort(new QName("http://www.example.org/S100037/", "S100037SOAP"), S100037.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100037
     */
    @WebEndpoint(name = "S100037SOAP")
    public S100037 getS100037SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100037/", "S100037SOAP"), S100037.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100037_EXCEPTION!= null) {
            throw S100037_EXCEPTION;
        }
        return S100037_WSDL_LOCATION;
    }

}
