
package com.sams.wsdl.S100454;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100454", targetNamespace = "http://www.example.org/S100454/", wsdlLocation = "file:/D:/wsdl/S100454.wsdl")
public class S100454_Service
    extends Service
{

    private final static URL S100454_WSDL_LOCATION;
    private final static WebServiceException S100454_EXCEPTION;
    private final static QName S100454_QNAME = new QName("http://www.example.org/S100454/", "S100454");

    static {
    	S100454_WSDL_LOCATION = com.sams.wsdl.S100454.S100454_Service.class.getResource("/wsdl/S100454.wsdl");
        WebServiceException e = null;
        if (S100454_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/S100454.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        S100454_EXCEPTION = e;
    }

    public S100454_Service() {
        super(__getWsdlLocation(), S100454_QNAME);
    }

    public S100454_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100454_QNAME, features);
    }

    public S100454_Service(URL wsdlLocation) {
        super(wsdlLocation, S100454_QNAME);
    }

    public S100454_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100454_QNAME, features);
    }

    public S100454_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100454_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100454
     */
    @WebEndpoint(name = "S100454SOAP")
    public S100454 getS100454SOAP() {
        return super.getPort(new QName("http://www.example.org/S100454/", "S100454SOAP"), S100454.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100454
     */
    @WebEndpoint(name = "S100454SOAP")
    public S100454 getS100454SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100454/", "S100454SOAP"), S100454.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100454_EXCEPTION!= null) {
            throw S100454_EXCEPTION;
        }
        return S100454_WSDL_LOCATION;
    }

}
