
package com.sams.wsdl.S100041;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100041", targetNamespace = "http://www.example.org/S100041/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100041 {


    /**
     * 
     * @param common
     * @return
     *     returns com.sams.wsdl.S100041.S100041TypeResponse
     */
    @WebMethod(operationName = "S100041", action = "http://www.example.org/S100041/S100041")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100041/", partName = "Common")
    public S100041TypeResponse s100041(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100041/", partName = "Common")
        S100041Type common);

}
