
package com.sams.wsdl.S100041;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100041", targetNamespace = "http://www.example.org/S100041/", wsdlLocation = "/wsdl/S100041.wsdl")
public class S100041_Service
    extends Service
{

    private final static URL S100041_WSDL_LOCATION;
    private final static WebServiceException S100041_EXCEPTION;
    private final static QName S100041_QNAME = new QName("http://www.example.org/S100041/", "S100041");

    static {
    	S100041_WSDL_LOCATION = com.sams.wsdl.S100041.S100041_Service.class.getResource("/wsdl/S100041.wsdl");
        WebServiceException e = null;
        if (S100041_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/S100041.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        S100041_EXCEPTION = e;
    }

    public S100041_Service() {
        super(__getWsdlLocation(), S100041_QNAME);
    }

    public S100041_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100041_QNAME, features);
    }

    public S100041_Service(URL wsdlLocation) {
        super(wsdlLocation, S100041_QNAME);
    }

    public S100041_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100041_QNAME, features);
    }

    public S100041_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100041_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100041
     */
    @WebEndpoint(name = "S100041SOAP")
    public S100041 getS100041SOAP() {
        return super.getPort(new QName("http://www.example.org/S100041/", "S100041SOAP"), S100041.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100041
     */
    @WebEndpoint(name = "S100041SOAP")
    public S100041 getS100041SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100041/", "S100041SOAP"), S100041.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100041_EXCEPTION!= null) {
            throw S100041_EXCEPTION;
        }
        return S100041_WSDL_LOCATION;
    }

}
