
package com.sams.wsdl.S100031;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100031", targetNamespace = "http://www.example.org/S100031/", wsdlLocation = "/wsdl/S100031.wsdl")
public class S100031_Service
    extends Service
{

    private final static URL S100031_WSDL_LOCATION;
    private final static WebServiceException S100031_EXCEPTION;
    private final static QName S100031_QNAME = new QName("http://www.example.org/S100031/", "S100031");

    static {
    	S100031_WSDL_LOCATION = com.sams.wsdl.S100031.S100031_Service.class.getResource("/wsdl/S100031.wsdl");
        WebServiceException e = null;
        if (S100031_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/S100031.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        S100031_EXCEPTION = e;
    }

    public S100031_Service() {
        super(__getWsdlLocation(), S100031_QNAME);
    }

    public S100031_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100031_QNAME, features);
    }

    public S100031_Service(URL wsdlLocation) {
        super(wsdlLocation, S100031_QNAME);
    }

    public S100031_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100031_QNAME, features);
    }

    public S100031_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100031_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100031
     */
    @WebEndpoint(name = "S100031SOAP")
    public S100031 getS100031SOAP() {
        return super.getPort(new QName("http://www.example.org/S100031/", "S100031SOAP"), S100031.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100031
     */
    @WebEndpoint(name = "S100031SOAP")
    public S100031 getS100031SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100031/", "S100031SOAP"), S100031.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100031_EXCEPTION!= null) {
            throw S100031_EXCEPTION;
        }
        return S100031_WSDL_LOCATION;
    }

}
