
package com.sams.wsdl.S100454;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "S100454", targetNamespace = "http://www.example.org/S100454/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface S100454 {


    /**
     * 
     * @param common
     * @return
     *     returns com.sams.wsdl.S100454.S100454TypeResponse
     */
    @WebMethod(operationName = "NewOperation", action = "http://www.example.org/S100454/NewOperation")
    @WebResult(name = "CommonRs", targetNamespace = "http://www.example.org/S100454/", partName = "Common")
    public S100454TypeResponse newOperation(
        @WebParam(name = "CommonRq", targetNamespace = "http://www.example.org/S100454/", partName = "Common")
        S100454Type common);

}
