
#####

server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  profiles:
    active: dev

  thymeleaf:
    cache: false

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  aop:
    proxy-target-class: true