server:
  port: 6688 #服务端口

spring:
  application:
    name: config-server #指定服务名configServer
  cloud:
    config:
      server:
        git: #配置git仓库地址
          uri: https://github.com/yindaiyong/learngit.git
          #username: zhangzhijun
          #password: 123456
eureka:
  client:
    registerWithEureka: true #?????????Eureka?????У?????true
    fetchRegistry: true #????Eureka?л??????????????true
    serviceUrl: #Eureka???????Eureka???????н???????
      defaultZone: http://admin:11111@127.0.0.1:8999/eureka/
  instance:
    prefer-ip-address: true #???????ip??????Eureka??????
