
package com.sams.wsdl.S100512;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100512", targetNamespace = "http://www.example.org/S100512/", wsdlLocation = "wsdl/S100512.wsdl")
public class S100512_Service
    extends Service
{

    private final static URL S100512_WSDL_LOCATION;
    private final static WebServiceException S100512_EXCEPTION;
    private final static QName S100512_QNAME = new QName("http://www.example.org/S100512/", "S100512");

    static {
    	S100512_WSDL_LOCATION = com.sams.wsdl.S100512.S100512_Service.class.getResource("/wsdl/S100512.wsdl");
        WebServiceException e = null;
        if (S100512_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/S100512.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        S100512_EXCEPTION = e;
    }

    public S100512_Service() {
        super(__getWsdlLocation(), S100512_QNAME);
    }

    public S100512_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100512_QNAME, features);
    }

    public S100512_Service(URL wsdlLocation) {
        super(wsdlLocation, S100512_QNAME);
    }

    public S100512_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100512_QNAME, features);
    }

    public S100512_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100512_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100512
     */
    @WebEndpoint(name = "S100512SOAP")
    public S100512 getS100512SOAP() {
        return super.getPort(new QName("http://www.example.org/S100512/", "S100512SOAP"), S100512.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100512
     */
    @WebEndpoint(name = "S100512SOAP")
    public S100512 getS100512SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100512/", "S100512SOAP"), S100512.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100512_EXCEPTION!= null) {
            throw S100512_EXCEPTION;
        }
        return S100512_WSDL_LOCATION;
    }

}
