
package com.sams.wsdl.S100434;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "S100434", targetNamespace = "http://www.example.org/S100434/", wsdlLocation = "file:/D:/wsdl/S100434.wsdl")
public class S100434_Service
    extends Service
{

    private final static URL S100434_WSDL_LOCATION;
    private final static WebServiceException S100434_EXCEPTION;
    private final static QName S100434_QNAME = new QName("http://www.example.org/S100434/", "S100434");

    static {
    	S100434_WSDL_LOCATION = com.sams.wsdl.S100434.S100434_Service.class.getResource("/wsdl/S100434.wsdl");
        WebServiceException e = null;
        if (S100434_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/S100434.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        S100434_EXCEPTION = e;
    }
    public S100434_Service() {
        super(__getWsdlLocation(), S100434_QNAME);
    }

    public S100434_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), S100434_QNAME, features);
    }

    public S100434_Service(URL wsdlLocation) {
        super(wsdlLocation, S100434_QNAME);
    }

    public S100434_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, S100434_QNAME, features);
    }

    public S100434_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public S100434_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns S100434
     */
    @WebEndpoint(name = "S100434SOAP")
    public S100434 getS100434SOAP() {
        return super.getPort(new QName("http://www.example.org/S100434/", "S100434SOAP"), S100434.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns S100434
     */
    @WebEndpoint(name = "S100434SOAP")
    public S100434 getS100434SOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/S100434/", "S100434SOAP"), S100434.class, features);
    }

    private static URL __getWsdlLocation() {
        if (S100434_EXCEPTION!= null) {
            throw S100434_EXCEPTION;
        }
        return S100434_WSDL_LOCATION;
    }

}
