server:
  port: 8087


eureka:
  client:
    registerWithEureka: true #?????????Eureka?????§µ?????true
    fetchRegistry: true #????Eureka?§Ý??????????????true
    serviceUrl: #Eureka???????Eureka???????§ß???????
      defaultZone: http://admin:11111@127.0.0.1:8999/eureka/
  instance:
    prefer-ip-address: true #???????ip??????Eureka??????
spring:
  application:
    name: ydy-item
